say: 在插件目录下的config.yml中的say:后面更改要输出的内容
#是否开启dishao插件权限管理模块
permissions: true
#给予非op玩家的权限
permissions-list:
  - dishao.help
  - dishao.tell
  - dishao.out
  - dishao.zisha
  - bukkit.command.tps
#非op玩家关闭的权限
off-permissions-list:
  - minecraft.command.seed
#插件启动时检测更新
detect-updates: true
#服务器标题
server-motd:
  #是否开启标题功能
  enable: true
  #服务器标题列表("%nl%"代表换行)
  motd-list:
    - 第一行%nl%第二行
  #每个标题等待时间(ms)
  motd-time: 3000
  #加载标题输出
  load-print: true
  #图标
  motd-icon: favicon.png
#超级用户
superuser: ''
#名字范围
name-range: ^[A-Za-z\u4e00-\u9fa50-9_\-]+$
#正版验证查询请在网络通畅的情况下开启(更改后请重启服务器,reload对该选项无效)
player-online-check: false
#无法连接正版验证API时的踢出显示
can_not_connect_API: 无法连接正版验证api,请重试,若多次出现该错误请联系服主关闭正版检测功能或更换正版账号不允许的用户名
#正版验证API请求数到达上限时的踢出显示
too_many_queries: 正版验证api查询次数达到峰值,请稍后再试(最多等待10分钟)
#正版验证API请求超时的踢出显示
time_out: 正版验证api连接超时,请重试
#玩家进入游戏的消息("%player%"表示玩家名字)
join-message: §9玩家%player%加入了游戏!
#玩家退出游戏的消息("%player%"表示玩家名字)
quit-message: §c玩家%player%退出了游戏!
#正版玩家的前缀(没有请用双引号代替,只对tab列表和聊天栏有效)
online-player-prefix: §a[正版玩家]§r
#输入/help后向玩家发送的内容
help: §c服主没有配置帮助
#tpa请求的保留时间(ms)
tpa-keep-time: 120000
