name: dishao
main: vip.dicloud.dishao
<<<<<<< Updated upstream
version: 1.11.2-R
=======
version: 1.11.4-B
>>>>>>> Stashed changes
api-version: 1.16
authors: [ DicloudStudio ]
commands:
  zisha:
    permission: "dishao.zisha"
    permission-message: "§4你没有使用该指令的权限!"
    aliases:
      - "514"
  back:
    permission: "dishao.back"
    permission-message: "§4你没有使用该指令的权限!"
    aliases:
      - "back"
  sethome:
    permission: "dishao.sethome"
    permission-message: "§4你没有使用该指令的权限!"
    aliases:
      - "sethome"
  home:
    permission: "dishao.home"
    permission-message: "§4你没有使用该指令的权限!"
    aliases:
      - "home"
  help:
    permission: "dishao.help"
    permission-message: "§4你没有使用该指令的权限!"
    aliases:
      - "help"
  tell:
    permission: "dishao.tell"
    permission-message: "§4你没有使用该指令的权限!"
    aliases:
      - "w"
      - "tell"
      - "msg"
  out:
    permission: "dishao.out"
    permission-message: "§4你没有使用该指令的权限!"
    aliases:
      - "out"
  tp:
    permission: "dishao.tp"
    permission-message: "§4你没有使用该指令的权限!"
    aliases:
      - "tp"
  kick:
    permission: "dishao.kick"
    permission-message: "§4你没有使用该指令的权限!"
    aliases:
      - "kick"
  dishao:
    permission: "dishao.main_command"
    permission-message: "§4你没有使用该指令的权限!"
    aliases:
      - "dishao"
      - "ds"
  playerinfo:
    permission: "dishao.playerinfo"
    permission-message: "§4你没有使用该指令的权限!"
    aliases:
      - "playerinfo"
      - "pi"
  playerinfolist:
    aliases:
      - "playerinfolist"
      - "pil"
  image:
    permission: "dishao.image"
    permission-message: "§4你没有使用该指令的权限!"
    aliases:
      - "image"
      - "img"
  hat:
    permission: "dishao.hat"
    permission-message: "§4你没有使用该指令的权限!"
    aliases:
      - "hat"
  tpa:
    permission: "dishao.tpa"
    permission-message: "§4你没有使用该指令的权限!"
    aliases:
      - "tpa"
  tpaccept:
    aliases:
      - "tpaccept"
  tpdeny:
    aliases:
      - "tpaccept"
permissions:
  dishao.tp:
    description: Dishao plugins tp command
  dishao.tell:
    default: true
  dishao.help:
    default: true
  dishao.out:
    default: true
  dishao.zisha:
    default: true
  dishao.kick:
    default: op
  dishao.main_command.info:
    default: op
  dishao.main_command:
    default: op
  dishao.main_command.config:
    default: op
  dishao.main_command.reload:
    default: op
  dishao.playerinfo:
    default: op
  dishao.image:
    default: op
  dishao.back:
    default: op
  dishao.sethome:
    default: op
  dishao.home:
    default: op
  dishao.hat:
    default: true
  dishao.tpa:
    default: op