name: dishao
main: vip.dicloud.dishao
version: 1.11.3-R
api-version: 1.16
authors: [ DicloudStudio ]
commands:
  zisha:
    permission: "dishao.zisha"
    permission-message: "§4你没有使用该指令的权限!"
    aliases:
      - "514"
  help:
    permission: "dishao.help"
    permission-message: "§4你没有使用该指令的权限!"
    aliases:
      - "help"
  tell:
    permission: "dishao.tell"
    permission-message: "§4你没有使用该指令的权限!"
    aliases:
      - "w"
      - "tell"
      - "msg"
  out:
    permission: "dishao.out"
    permission-message: "§4你没有使用该指令的权限!"
    aliases:
      - "out"
  tp:
    permission: "dishao.tp"
    permission-message: "§4你没有使用该指令的权限!"
    aliases:
      - "tp"
  kick:
    permission: "dishao.kick"
    permission-message: "§4你没有使用该指令的权限!"
    aliases:
      - "kick"
  dishao:
    permission: "dishao.main_command"
    permission-message: "§4你没有使用该指令的权限!"
    aliases:
      - "dishao"
      - "ds"
  playerinfo:
    permission: "dishao.playerinfo"
    permission-message: "§4你没有使用该指令的权限!"
    aliases:
      - "playerinfo"
      - "pi"
  playerinfolist:
    aliases:
      - "playerinfolist"
      - "pil"
  image:
    permission: "dishao.image"
    permission-message: "§4你没有使用该指令的权限!"
    aliases:
      - "image"
      - "img"
permissions:
  dishao.tp:
    description: Dishao plugins tp command
  dishao.tell:
    description: Dishao plugins tell command
  dishao.help:
    description: Dishao plugins help command
  dishao.out:
    description: Dishao plugins out command
  dishao.zisha:
    description: Dishao plugins zisha command
  dishao.kick:
    description: Dishao plugins kick command
  dishao.main_command.info:
    description: Dishao plugins main_info command
  dishao.main_command:
    description: Dishao plugins main command
  dishao.main_command.config:
    description: Dishao plugins main_config command
  dishao.main_command.reload:
    description: Dishao plugins main_reload command
  dishao.playerinfo:
    description: Dishao plugins main_reload command
  dishao.image:
    description: Dishao plugins main_reload command
  dishao.tpa:
    description: Dishao plugins main_reload command